version: "3"
services:
  db:
    image: postgres:latest
    container_name: yangtube
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./data:/var/lib/postgresql/data
